---
- name: Install RHEL/Fedora Web Console (Cockpit)
  ansible.builtin.include_role:
    name: linux-system-roles.cockpit
  vars:
    cockpit_packages: full

- name: Configure Firewall for Web Console
  ansible.builtin.include_role:
    name: linux-system-roles.firewall
  vars:
    firewall:
      service: cockpit
      state: enabled
  when: not cicd_test|bool
