---
- name: Add remote user to system
  ansible.builtin.user:
    name: "{{ xrdp_remote_user }}"
    state: present

- name: Set remote user password
  ansible.builtin.command: passwd -S "{{ xrdp_remote_user }}"
  register: passwd_status
  changed_when: false

- name: Set remote user password if not already set
  ansible.builtin.command: passwd "{{ xrdp_remote_user }}"
  args:
    stdin: "{{ xrdp_remote_user_password }}"
  changed_when: passwd_status.stdout !=  xrdp_remote_user

- name: Debug password change
  ansible.builtin.debug:
    msg: "Password changed for remote user"
  when: passwd_status.stdout != xrdp_remote_user
  no_log: true

- name: Add remote user to wheel group
  ansible.builtin.user:
    name: "{{ xrdp_remote_user }}"
    groups: wheel
    append: true

- name: Add remote user to sudoers
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ xrdp_remote_user }}"
    line: "{{ xrdp_remote_user }} ALL=(root) NOPASSWD:ALL"
    create: true
    mode: 0644
    validate: "visudo -cf %s"

- name: Set permissions for sudoers file
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ xrdp_remote_user }}"
    owner: root
    group: root
    mode: "0440"
