---
- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: libvirt_host_networks
  register: myresults

- name: Validate variables are defined
  ansible.builtin.include_tasks: verify_variables.yml

- name: Ensure required packages are installed
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ required_rpm_packages }}"

- name: Configure shell extras
  ansible.builtin.include_tasks: configure_shell.yml
  when: configure_shell|bool

- name: Setup Cockpit
  ansible.builtin.include_tasks: cockpit_setup.yml
  when: enable_cockpit|bool and ansible_distribution != "Rocky"

- name: Setup Rocky Linux
  ansible.builtin.include_tasks: rocky_linux.yml
  when: enable_cockpit|bool and ansible_distribution == "Rocky"

- name: Check if GUID environment variable is set
  command: echo ${GUID}
  register: guid_result
  changed_when: false
  ignore_errors: true

- name: Run the next task if GUID is set
  debug:
    msg: "GUID is set and its value is {{ guid_result.stdout }}"
  when: guid_result.stdout != ""

- name: Setup xRDP on RHPDS
  ansible.builtin.include_tasks: rhpds_instance.yml
  when: enable_cockpit|bool and guid_result.stdout != ""

- name: Setup Remote User for XRDP
  ansible.builtin.include_tasks: configure_remote_user.yml
  when: enable_cockpit|bool and  guid_result.stdout != ""

- name: Setup Libvirt
  ansible.builtin.include_tasks: libvirt_setup.yml
  when: lib_virt_setup|bool
