---
- name: Install Server with GUI group
  ansible.builtin.dnf:
    name: "@Server with GUI"
    state: present
  become: true

- name: Install EPEL repository using yum
  ansible.builtin.command:
    cmd: sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y
  become: true

- name: Update package cache
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Install tigervnc-server and xrdp packages
  ansible.builtin.dnf:
    name:
      - tigervnc-server
      - xrdp
    state: present
  become: true

- name: Enable and start xrdp service
  ansible.builtin.systemd:
    name: xrdp
    enabled: true
    state: started
  become: true

- name: Configure firewall
  ansible.posix.firewalld:
    port: 3389/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true

- name: Install RHEL/Fedora Web Console (Cockpit)
  ansible.builtin.include_role:
    name: linux-system-roles.cockpit
  vars:
    cockpit_packages: full

- name: Configure Firewall for Web Console
  ansible.posix.firewalld:
    port: 9090/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true
