---
- name: Install EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present
  become: true

- name: Install Server group
  ansible.builtin.dnf:
    name: "@Server"
    state: present
  become: true

- name: Install xrdp package
  ansible.builtin.dnf:
    name: xrdp
    state: present
  become: true

- name: Enable and start xrdp service
  ansible.builtin.systemd:
    name: xrdp
    enabled: true
    state: started
  become: true

- name: Configure firewall
  ansible.posix.firewalld:
    port: 3389/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true

- name: Configure Firewall for Web Console
  ansible.posix.firewalld:
    port: 9090/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true
