- name: Ensure ~/.config exist
  file:
    path: "{{ user_homedir }}/.config"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0755'
  with_items: "{{ users }}"

- name: Deploy startship config for current user
  copy:
    src: "{{ starship_config }}"
    dest: "{{ user_homedir }}/.config/starship.toml"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  with_items: "{{ users }}"
