---
- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: libvirt_host_networks
  register: myresults

- name: Validate variables are defined
  include_tasks: verify_variables.yml

- name: Ensure required packages are installed
  ansible.builtin.shell: >
    rpm -q "{{ item }}" || yum install -y "{{ item }}" && echo true
  loop: "{{ required_rpm_pakcages }}"


- name: Install required python libraries
  become: true
  become_user: "{{ admin_user }}"
  ansible.builtin.pip:
    name: openshift
    extra_args: --user

- name: Configure shell extras
  include_tasks: configure_shell.yml
  when: configure_shell|bool

- name: Setup Libvirt
  include_tasks: libvirt_setup.yml

- name: Setup Cockpit
  include_tasks: cockpit_setup.yml
  when: enable_cockpit|bool
