---
- name: Get list of libvirt networks
  virt_net:
    command: list_nets
  register: libvirt_nets

- name: Ensure libvirt networks are setup
  vars:
    libvirt_network_name: "{{ libvirt_host_networks[libvirt_idx].name }}"
    net_mode: "{{ libvirt_host_networks[libvirt_idx].mode }}"
    net_create: "{{ libvirt_host_networks[libvirt_idx].create }}"
  when: libvirt_network_name in libvirt_nets.list_nets

  block:
    - name: Ensure libvirt nat network libvirt network is defined
      virt_net:
        name: "{{ libvirt_network_name }}"
        command: define
        xml: '{{ lookup("templates", "nat_network.xml.j2") }}'
      when: net_mode == 'nat' and net_create|bool

    - name: Ensure libvirt network  is active
      virt_net:
        name: "{{ libvirt_network_name }}"
        state: active

    - name: Ensure libvirt network  is started on boot
      virt_net:
        name: "Start {{ libvirt_network_name }} on boot"
        autostart: true
