---
- name: Get list of libvirt networks
  community.libvirt.virt_net:
    command: list_nets
  register: libvirt_nets

- name: Ensure libvirt networks are setup
  vars:
    net_name: "{{ libvirt_host_networks[libvirt_idx].name }}"
    net_mode: "{{ libvirt_host_networks[libvirt_idx].mode }}"
    net_create: "{{ libvirt_host_networks[libvirt_idx].create }}"
  when: net_name in libvirt_nets.list_nets

  block:
    - name: Ensure libvirt nat network libvirt network is defined
      community.libvirt.virt_net:
        name: "{{ net_name }}"
        command: define
        xml: '{{ lookup("templates", "nat_network.xml.j2") }}'
      when: net_mode == 'nat' and net_create|bool

    - name: Ensure libvirt network  is active
      community.libvirt.virt_net:
        name: "{{ net_name }}"
        state: active

    - name: Ensure libvirt network  is started on boot
      community.libvirt.virt_net:
        name: "{{ net_name }}"
        autostart: true
