---
- name: Install EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present
  become: true

- name: Update all packages
  ansible.builtin.dnf:
    name: '*'
    state: present
    update_cache: true
  become: true

- name: Install Server with GUI group
  ansible.builtin.dnf:
    name: "@Server with GUI"
    state: present
  become: true

- name: Install xrdp package
  ansible.builtin.dnf:
    name: xrdp
    state: present
  become: true

- name: Enable and start xrdp service
  ansible.builtin.systemd:
    name: xrdp
    enabled: true
    state: started
  become: true

- name: Configure firewall
  ansible.posix.firewalld:
    port: 3389/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true

- name: Install RHEL/Fedora Web Console (Cockpit)
  ansible.builtin.include_role:
    name: linux-system-roles.cockpit
  ignore_errors: true
  vars:
    cockpit_packages: full

- name: Configure Firewall for Web Console
  ansible.builtin.include_role:
    name: linux-system-roles.firewall
  vars:
    firewall:
      service: cockpit
      state: enabled
  ignore_errors: true
  when: not cicd_test|bool
