---
- name: Create k9s installation directory
  ansible.builtin.file:
    path: /usr/local/bin/k9s
    state: directory
    mode: '0755'

- name: Download k9s binary
  ansible.builtin.get_url:
    url: "https://github.com/derailed/k9s/releases/download/v0.27.3/k9s_Linux_amd64.tar.gz"
    dest: /tmp/k9s.tar.gz
    checksum: "sha256:5f8e2e9b0b9b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b"
    timeout: 30
    retries: 5
    delay: 10
  register: download_result
  until: download_result is success
  ignore_errors: true

- name: Extract k9s binary
  ansible.builtin.unarchive:
    src: /tmp/k9s.tar.gz
    dest: /usr/local/bin/k9s
    remote_src: true
    creates: /usr/local/bin/k9s/k9s
    extra_opts:
      - --strip-components=1

- name: Set k9s executable permissions
  ansible.builtin.file:
    path: /usr/local/bin/k9s/k9s
    mode: '0755'

- name: Create k9s symlink
  ansible.builtin.file:
    src: /usr/local/bin/k9s/k9s
    dest: /usr/local/bin/k9s
    state: link

- name: Verify k9s installation
  ansible.builtin.command: k9s version
  register: k9s_version
  changed_when: false

- name: Display k9s version
  ansible.builtin.debug:
    msg: "k9s version: {{ k9s_version.stdout }}"
