---
- name: Converge
  hosts: molecule
  remote_user: lab-user
  become: true
  vars:
    admin_user: molecule
    libvirt_user: "ansible"
    domain: test.local
    dns_forwarder: "1.1.1.1"
    lib_virt_setup: true
    enable_cockpit: true
    configure_shell: true
    kvm_host_libvirt_dir: /var/lib/libvirt/images
    kvmhost_bridge_device: br0
    libvirt_networks:
      - name: default
        bridge: br0
    kvm_host_domain: test.local

  collections:
    - community.libvirt
    - ansible.posix
    - community.general
    - fedora.linux_system_roles
    - ansible.netcommon

  roles:
    - name: linux-system-roles.network
      src: https://github.com/linux-system-roles/network


  pre_tasks:
    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false

  roles:
    - role: ../../roles/edge_hosts_validate
    - role: ../../roles/swygue_lvm
    - role: ../../roles/kvmhost_setup
