---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kvmhost-test
    image: rockylinux:9
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: true
  inventory:
    links:
      hosts: ../qubinode_navigator/inventories/rhel9-equinix/hosts
      group_vars: ../qubinode_navigator/inventories/rhel9-equinix/group_vars/
verifier:
  name: testinfra
  options:
    verbose: true
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
