---
dependency:
  name: galaxy
driver:
  # Uncomment below for Podman (default for local development)
  name: podman
  options:
    podman_binary: /usr/bin/podman
    podman_extra_args: --log-level=debug

  # Uncomment below for Docker (use in CI/CD)
  # name: docker
  # options:
  #   docker_binary: /usr/bin/docker
  #   docker_extra_args: --log-level=debug
platforms:
  - name: kvmhost-test
    image: docker.io/rockylinux/rockylinux:9-ubi-init
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    pre_build_image: false
    build:
      context: .
      dockerfile: Dockerfile
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      roles_path: /home/lab-user/qubinode_kvmhost_setup_collection/roles
    ssh_connection:
      pipelining: true
  inventory:
    links:
      hosts: ../../inventories/test/hosts
      group_vars: ../../inventories/test/group_vars/
lint: |
  set -e
  yamllint .
  ansible-lint roles/kvmhost_setup/

verifier:
  name: testinfra
  options:
    verbose: true
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
