---
collections:
  - ansible.posix
  - community.general
  - community.libvirt
  - fedora.linux_system_roles
  - ansible.netcommon

roles:
  - src: https://github.com/linux-system-roles/network
    name: linux-system-roles.network
